# Generated by Django 4.2.18 on 2025-03-10 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customlist',
            name='item_id',
        ),
    ]
