# Generated by Django 4.2.18 on 2025-01-31 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='biography',
            new_name='bio',
        ),
    ]
