# Generated by Django 4.2.18 on 2025-02-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_bio_alter_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='played_games',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='read_books',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='to_play_games',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='to_read_books',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='to_watch_moviesTV',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='watched_movies',
            field=models.JSONField(default=list),
        ),
    ]
