# Generated by Django 4.2.18 on 2025-03-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_futurewatchlist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurewatchlist',
            name='item_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
