# Generated by Django 4.2.18 on 2025-03-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_futurewatchlist_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurewatchlist',
            name='item_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
