# Generated by Django 4.2.18 on 2025-02-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_played_games_profile_read_books_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='played_games',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='read_books',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='to_play_games',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='to_read_books',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='to_watch_moviesTV',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='watched_movies',
        ),
        migrations.AddField(
            model_name='profile',
            name='watchlist',
            field=models.JSONField(default=dict),
        ),
    ]
