# Generated by Django 4.2.18 on 2025-02-26 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_rename_watchlist_profile_watchlist_past_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='watchlist_future',
        ),
        migrations.CreateModel(
            name='FutureWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('books', 'Books'), ('movies', 'Movies'), ('games', 'Games')], max_length=20)),
                ('item_id', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category', 'item_id')},
            },
        ),
    ]
