# Generated by Django 4.2.18 on 2025-03-02 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_futurewatchlist_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futurewatchlist',
            name='item_name',
        ),
    ]
