# Generated by Django 4.2.18 on 2025-03-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_futurewatchlist_item_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futurewatchlist',
            name='item_details',
        ),
    ]
