# Generated by Django 4.2.18 on 2025-03-05 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_favorite_title_favorite_date_added_customlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlist',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customlist',
            name='item_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
