# Generated by Django 4.2.18 on 2025-03-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customlist_date_added_customlist_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customlist',
            name='id',
        ),
        migrations.AddField(
            model_name='customlist',
            name='custom_list_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
