# Generated by Django 4.2.18 on 2025-03-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_customlist_custom_list_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_lists',
            field=models.ManyToManyField(to='accounts.customlist'),
        ),
    ]
