# Generated by Django 4.2.18 on 2025-03-09 03:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0021_fourfavorites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fourFavorites',
            new_name='fourFavorite',
        ),
    ]
