# Generated by Django 4.2.18 on 2025-03-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_rename_fourfavorites_fourfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='item_id',
            field=models.CharField(max_length=50),
        ),
    ]
