# Generated by Django 4.2.18 on 2025-03-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_favorite_image_url_favorite_title_favorite_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
