# Generated by Django 4.2.18 on 2025-03-09 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0024_favorite_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='description',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='title',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='year',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='item_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
