# Generated by Django 4.2.18 on 2025-03-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_favorite_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
