# Generated by Django 4.2.18 on 2025-03-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_futurewatchlist_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futurewatchlist',
            old_name='image_url',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='futurewatchlist',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
