# Generated by Django 4.2.18 on 2025-03-09 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0030_alter_favorite_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourfavorite',
            name='category',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show'), ('book', 'Book'), ('boardgame', 'Board Game'), ('videogame', 'Video Game')], default='media', max_length=20),
        ),
        migrations.AddField(
            model_name='fourfavorite',
            name='item_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='fourfavorite',
            unique_together={('user', 'category', 'item_id')},
        ),
        migrations.RemoveField(
            model_name='fourfavorite',
            name='fourFavorites',
        ),
    ]
