# Generated by Django 4.2.18 on 2025-03-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_fourfavorite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourfavorite',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fourfavorite',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fourfavorite',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fourfavorite',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
