# Generated by Django 4.2.18 on 2025-03-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_fourfavorite_description_fourfavorite_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fourFavorite',
        ),
    ]
