# Generated by Django 4.2.18 on 2025-03-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0002_delete_mediaitem'),
        ('lists', '0001_initial'),
        ('accounts', '0035_fourfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='custom_lists',
            field=models.ManyToManyField(to='lists.customlist'),
        ),
        migrations.DeleteModel(
            name='CustomList',
        ),
    ]
