# Generated by Django 4.2.18 on 2025-03-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_remove_customlist_item_id'),
        ('accounts', '0036_alter_profile_custom_lists_delete_customlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='custom_lists',
            field=models.ManyToManyField(blank=True, to='lists.customlist'),
        ),
    ]
