# Generated by Django 4.2.18 on 2025-03-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_profile_custom_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastwatchlist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pastwatchlist',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pastwatchlist',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pastwatchlist',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
