# Generated by Django 4.2.18 on 2025-03-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_rename_image_url_favorite_image_and_more'),
        ('accounts', '0038_pastwatchlist_description_pastwatchlist_image_and_more'),
    ]

    operations = [
    ]
