# Generated by Django 4.2.18 on 2025-03-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_merge_20250310_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='watchlist_past',
        ),
    ]
