# Generated by Django 4.2.18 on 2025-03-10 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0035_fourfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='mediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show'), ('book', 'Book'), ('boardgame', 'Board Game'), ('videogame', 'Video Game')], max_length=20)),
                ('item_id', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('year', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('custom_list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customList', to='accounts.customlist')),
            ],
            options={
                'ordering': ['-date_added'],
                'unique_together': {('custom_list_id', 'category', 'item_id')},
            },
        ),
    ]
