# Generated by Django 4.2.18 on 2025-03-10 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mediaItem',
        ),
    ]
